# Generated by Django 4.2.27 on 2026-04-15 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='脚本名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='脚本描述')),
                ('interface_doc', models.TextField(verbose_name='接口文档')),
                ('script_content', models.TextField(verbose_name='脚本内容')),
                ('script_file', models.CharField(blank=True, default='', max_length=500, verbose_name='脚本文件路径')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪'), ('running', '执行中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试脚本',
                'verbose_name_plural': '测试脚本',
                'db_table': 'test_scripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='状态')),
                ('result_file', models.CharField(blank=True, default='', max_length=500, verbose_name='结果文件路径')),
                ('report_file', models.CharField(blank=True, default='', max_length=500, verbose_name='报告文件路径')),
                ('total_cases', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('duration', models.FloatField(default=0, verbose_name='执行时长(秒)')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='test_execution.testscript', verbose_name='测试脚本')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'test_tasks',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('html', 'HTML报告'), ('json', 'JSON数据'), ('allure', 'Allure报告')], default='html', max_length=50, verbose_name='报告类型')),
                ('report_content', models.TextField(verbose_name='报告内容')),
                ('ai_analysis', models.TextField(blank=True, default='', verbose_name='AI分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='test_execution.testtask', verbose_name='测试任务')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'test_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
