# Generated by Django 4.2.27 on 2026-04-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='用例标题')),
                ('description', models.TextField(verbose_name='用例描述')),
                ('requirements', models.TextField(verbose_name='需求描述')),
                ('code_snippet', models.TextField(blank=True, default='', verbose_name='代码片段')),
                ('test_steps', models.TextField(verbose_name='测试步骤')),
                ('expected_results', models.TextField(verbose_name='预期结果')),
                ('case_type', models.CharField(choices=[('functional', '功能测试用例'), ('interface', '接口测试用例')], max_length=20, verbose_name='用例类型')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'test_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
